sudo: required

language: ruby

services:
  - docker

install:
  - sudo curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get -y -qq install docker-engine
  - sudo apt-get update -qq
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.11.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - cp docker-env.dist docker-env
  - docker-compose up -d
  - docker images
  - docker ps
  - docker-compose logs
