web:
  build: web
  env_file: docker-env
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
    - "10081:10081"
    - "10082:10082"
    - "10083:10083"
  volumes:
    -
  links:
    - percona
    - blackfire
  tty: true

percona:
  build: percona
  env_file: docker-env
  ports:
    - "3306:3306"
  volumes:
    - /etc/mysql
    - /var/lib/mysql
  tty: true

blackfire:
  image: blackfire/blackfire
  env_file: docker-env
  ports:
    - "8707:8707"

#nodejs:
#  build: nodejs
#  env_file: docker-env
#  ports:
#    - "npm
