version: "3"

services:
  apache:
    build: apache
    env_file: docker-env
    depends_on:
      - php
    ports:
      - 443:443
    volumes:
      - ~/www:/var/www/html:rw,delegated
    tty: true

  blackfire:
    image: blackfire/blackfire:latest
    env_file: docker-env
    depends_on:
      - apache
      - php

  maildev:
    image: djfarrelly/maildev:latest
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - 1080:80

  mongo:
    image: mongo:3.6
    env_file: docker-env
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    tty: true

  mysql:
    build: mysql
    env_file: docker-env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  php:
    build: php
    env_file: docker-env
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - ~/www:/var/www/html:rw,delegated
      # SSH socket
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    tty: true

  redis:
    image: redis:4-alpine
    env_file: docker-env
    tty: true

volumes:
  mongo: {}
  mysql: {}
