version: "3"

services:
  apache:
    build: apache
    env_file: docker-env
    volumes:
      - "~/www:/var/www/html:rw,delegated"
    tty: true

  blackfire:
    image: blackfire/blackfire:latest
    env_file: docker-env
    depends_on:
      - apache

  maildev:
    image: djfarrelly/maildev:latest
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - "1080:80"

  mongo:
    image: mongo:latest
    env_file: docker-env
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
    tty: true

  mysql:
    build: mysql
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

  nginx:
    build: nginx
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - "80:80"
      - "443:443"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    tty: true

volumes:
  mongo: {}
  mysql: {}
