web:
  build: web
  env_file: docker-env
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ~/www:/var/www/html
  links:
    - mysql
    - blackfire
  tty: true

mysql:
  build: mysql
  env_file: docker-env
  ports:
    - "3306:3306"
  volumes:
    - /etc/mysql
    - /var/lib/mysql
    - ~/shared-folders/dumps:/root/dumps
  tty: true

blackfire:
  image: blackfire/blackfire
  env_file: docker-env
  ports:
    - "8707:8707"

nodejs:
  build: nodejs
  env_file: docker-env
  ports:
   - "8888:8888"
  volumes_from:
   - web
