web:
  build: web
  env_file: docker-env
  ports:
    - "80:80"
    - "443:443"
    - "10081:10081"
    - "10082:10082"
    - "10083:10083"
  volumes:
    - ~/www:/var/www/html
  links:
    - mysql
    - blackfire
  tty: true

mysql:
  build: mysql
  env_file: docker-env
  ports:
    - "3306:3306"
  volumes:
    - /etc/mysql
    - /var/lib/mysql
  tty: true

blackfire:
  image: blackfire/blackfire
  env_file: docker-env
  ports:
    - "8707:8707"
