version: "3"

services:
  apache:
    build: apache
    env_file: docker-env
    ports:
      - "8080:80"
    volumes:
      - "~/www:/var/www/html:rw,delegated"
    tty: true

  blackfire:
    image: blackfire/blackfire
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - "8707:8707"

  maildev:
    image: djfarrelly/maildev
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - "1080:80"

  mongo:
    image: mongo:latest
    env_file: docker-env
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
    tty: true

  mysql:
    build: mysql
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

  nginx:
    build: nginx
    env_file: docker-env
    depends_on:
      - varnish
    ports:
      - "443:443"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    ports:
      - "6379:6379"
    tty: true

  varnish:
    image: ajardin/varnish:latest
    env_file: docker-env
    depends_on:
      - apache
    ports:
      - "80:8080"
      - "6082:6082"
    tty: true

volumes:
  mongo: {}
  mysql: {}
