version: "2.1"

services:
  web:
    build: web
    env_file: docker-env
    ports:
      - "8080:80"
      - "10081:10081"
      - "10082:10082"
      - "10083:10083"
    volumes:
      - "~/www:/var/www/html"
    tty: true

  percona:
    image: percona:5.6
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "./docker/percona:/etc/mysql/conf.d"
      - "percona:/var/lib/mysql"
    tty: true

  mongo:
    image: mongo:latest
    env_file: docker-env
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    ports:
      - "6379:6379"
    tty: true

  varnish:
    build: varnish
    env_file: docker-env
    depends_on:
      - web
    ports:
      - "80:8080"
      - "6082:6082"
    tty: true

volumes:
  percona: {}
  mongo: {}
