web:
  build: web
  env_file: .env
  ports:
    - "8080:8080"
    - "10081:10081"
    - "10082:10082"
    - "10083:10083"
  volumes:
    - ~/www:/var/www/html
  links:
    - percona
    - mongo

percona:
  build: percona
  env_file: .env
  ports:
    - "3306:3306"
  volumes:
    - /etc/mysql
    - /var/lib/mysql

mongo:
  build: mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/db

varnish:
  build: varnish
  env_file: .env
  ports:
    - "80:80"
    - "6082:6082"
  links:
    - web
