#!/bin/bash

LOGS_DIRECTORY='/var/log/docker'
if [ ! -d "$LOGS_DIRECTORY" ]; then
    mkdir ${LOGS_DIRECTORY}
fi

function format_date() {
    DATE=`date "+%Y-%m-%d %H:%M:%S"`
}

function start_progress() {
    format_date
    echo "[$DATE] docker.INFO: ${STEP_NAME}..."
}

RESET="\033[0m" ; GREEN="\033[32m" ; RED="\033[31m"
function print_status() {
    if [ $? -eq 0 ]; then
        format_date
        echo -e "[$DATE] docker.INFO: ${STEP_NAME} done. ${GREEN}[OK]${RESET}"
    else
        format_date
        echo -e "[$DATE] docker.ERROR: An error occurred during the ${STEP_NAME}, please check the logs: ${STEP_LOGS}. ${RED}[FAIL]${RESET}"
    fi
}

STEP_NAME='Zend Server configuration' ; STEP_LOGS="${LOGS_DIRECTORY}/zend-server.log"
start_progress
/bin/bash /usr/local/bin/extra/zend-server.sh > ${STEP_LOGS} 2>&1
print_status

STEP_NAME='Virtual hosts creation' ; STEP_LOGS="${LOGS_DIRECTORY}/vhosts.log"
start_progress
/bin/bash /usr/local/bin/extra/vhosts.sh > ${STEP_LOGS} 2>&1
print_status

STEP_NAME='Varnish configuration' ; STEP_LOGS="${LOGS_DIRECTORY}/varnish.log"
start_progress
/bin/bash /usr/local/bin/extra/varnish.sh > ${STEP_LOGS} 2>&1
print_status

STEP_NAME='Databases configuration' ; STEP_LOGS="${LOGS_DIRECTORY}/databases.log"
start_progress
/bin/bash /usr/local/bin/extra/databases.sh > ${STEP_LOGS} 2>&1
print_status
